apiVersion: v1
kind: Pod
metadata:
  name: oom-test
  namespace: ai-apps
spec:
  containers:
  - name: memory-hog
    image: python:3.9-slim
    command: ["python", "-c", "a = ' ' * 300 * 1024 * 1024; import time; time.sleep(300)"]
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"

