apiVersion: v1
kind: Pod
metadata:
  name: unhealthy-probe-pod
  namespace: ai-apps
  labels:
    app: unhealthy-probe
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
          - cat
          - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 5
